In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
customers = pd.read_csv("../data/raw/customers.csv")
customers.head()

,customer_id,customer_name,age,gender,state,customer_segment,join_date,annual_income
0,1,Customer 1,28,Male,Florida,Mass Affluent,2024-08-02,79106.36
1,2,Customer 2,27,Other,North Carolina,High Value,2025-02-17,159908.35
2,3,Customer 3,22,Male,New York,Mass Affluent,2021-03-07,141178.16
3,4,Customer 4,56,Male,North Carolina,Entry,2021-02-24,78496.94
4,5,Customer 5,38,Male,California,Entry,2024-04-21,104855.11

In [5]:
customers.shape

(5000, 8)

In [6]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   int64
 1   customer_name     5000 non-null   str
 2   age               5000 non-null   int64
 3   gender            5000 non-null   str
 4   state             5000 non-null   str
 5   customer_segment  5000 non-null   str
 6   join_date         5000 non-null   str
 7   annual_income     5000 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 312.6 KB

In [7]:
customers.describe()

       customer_id          age  annual_income
count  5000.000000  5000.000000    5000.000000
mean   2500.500000    47.829000  138755.619950
std    1443.520003    15.747818   64068.776298
min       1.000000    21.000000   30020.320000
25%    1250.750000    34.000000   81442.417500
50%    2500.500000    48.000000  138162.025000
75%    3750.250000    61.000000  194548.372500
max    5000.000000    75.000000  249994.860000

In [8]:
customers.describe(include="object")

/var/folders/0c/k6yktn7j7sx5n2yj_0g27zqm0000gn/T/ipykernel_29142/1913638412.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  customers.describe(include="object")

       customer_name gender       state customer_segment   join_date
count           5000   5000        5000             5000        5000
unique          5000      3          10                4        1687
top       Customer 1   Male  California            Entry  2023-02-12
freq               1   1679         531             1288          10

In [10]:
accounts = pd.read_csv("../data/raw/accounts.csv")

transactions = pd.read_csv("../data/raw/transactions.csv")

products = pd.read_csv("../data/raw/products.csv")

In [ ]:
print(customers.isnull().sum())
print(accounts.isnull().sum())
print(transactions.isnull().sum())
print(products.isnull().sum())

customer_id         0
customer_name       0
age                 0
gender              0
state               0
customer_segment    0
join_date           0
annual_income       0
dtype: int64
account_id      0
customer_id     0
account_type    0
open_date       0
status          0
balance         0
dtype: int64
transaction_id       0
customer_id          0
account_id           0
transaction_date     0
transaction_type     0
amount               0
merchant_category    0
channel              0
status               0
dtype: int64
product_id          0
product_name        0
product_category    0
interest_rate       0
dtype: int64