In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
customers = pd.read_csv("../data/raw/customers.csv")
customers.head()

,customer_id,customer_name,age,gender,state,customer_segment,join_date,annual_income
0,1,Customer 1,28,Male,Florida,Mass Affluent,2024-08-02,79106.36
1,2,Customer 2,27,Other,North Carolina,High Value,2025-02-17,159908.35
2,3,Customer 3,22,Male,New York,Mass Affluent,2021-03-07,141178.16
3,4,Customer 4,56,Male,North Carolina,Entry,2021-02-24,78496.94
4,5,Customer 5,38,Male,California,Entry,2024-04-21,104855.11

In [3]:
customers.shape

(5000, 8)

In [4]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   int64
 1   customer_name     5000 non-null   str
 2   age               5000 non-null   int64
 3   gender            5000 non-null   str
 4   state             5000 non-null   str
 5   customer_segment  5000 non-null   str
 6   join_date         5000 non-null   str
 7   annual_income     5000 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 312.6 KB

In [5]:
customers.describe()

       customer_id          age  annual_income
count  5000.000000  5000.000000    5000.000000
mean   2500.500000    47.829000  138755.619950
std    1443.520003    15.747818   64068.776298
min       1.000000    21.000000   30020.320000
25%    1250.750000    34.000000   81442.417500
50%    2500.500000    48.000000  138162.025000
75%    3750.250000    61.000000  194548.372500
max    5000.000000    75.000000  249994.860000

In [6]:
customers.describe(include="object")

/var/folders/0c/k6yktn7j7sx5n2yj_0g27zqm0000gn/T/ipykernel_45026/1913638412.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  customers.describe(include="object")

       customer_name gender       state customer_segment   join_date
count           5000   5000        5000             5000        5000
unique          5000      3          10                4        1687
top       Customer 1   Male  California            Entry  2023-02-12
freq               1   1679         531             1288          10

In [7]:
accounts = pd.read_csv("../data/raw/accounts.csv")

transactions = pd.read_csv("../data/raw/transactions.csv")

products = pd.read_csv("../data/raw/products.csv")

In [8]:
print(customers.isnull().sum())
print("-------------------------------")
print(accounts.isnull().sum())
print("-------------------------------")
print(transactions.isnull().sum())
print("-------------------------------")
print(products.isnull().sum())

customer_id         0
customer_name       0
age                 0
gender              0
state               0
customer_segment    0
join_date           0
annual_income       0
dtype: int64
-------------------------------
account_id      0
customer_id     0
account_type    0
open_date       0
status          0
balance         0
dtype: int64
-------------------------------
transaction_id       0
customer_id          0
account_id           0
transaction_date     0
transaction_type     0
amount               0
merchant_category    0
channel              0
status               0
dtype: int64
-------------------------------
product_id          0
product_name        0
product_category    0
interest_rate       0
dtype: int64

In [9]:
customers.duplicated().sum()
accounts.duplicated().sum()
transactions.duplicated().sum()

np.int64(0)

In [10]:
print(transactions["amount"].describe())
print("-------------------------------")
print(transactions["transaction_type"].value_counts())
print("-------------------------------")
print(transactions["channel"].value_counts())
print("-------------------------------")
print(transactions["status"].value_counts())

count    100000.000000
mean        371.595108
std        3072.682702
min           1.080000
25%          27.920000
50%          55.380000
75%         109.472500
max       49924.200000
Name: amount, dtype: float64
-------------------------------
transaction_type
Withdrawal    20228
Transfer      20042
Purchase      19967
Payment       19945
Deposit       19818
Name: count, dtype: int64
-------------------------------
channel
Online    20167
Branch    20131
Phone     19927
ATM       19925
Mobile    19850
Name: count, dtype: int64
-------------------------------
status
Completed    66683
Pending      16662
Failed       16655
Name: count, dtype: int64

In [11]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)

In [12]:
transactions["transaction_date"].min()

Timestamp('2024-01-01 00:00:00')

In [13]:
transactions["transaction_date"].max()

Timestamp('2025-12-31 00:00:00')

In [14]:
transactions.sort_values("amount", ascending=False).head(20)

,transaction_id,customer_id,account_id,transaction_date,transaction_type,amount,merchant_category,channel,status
38740,38741,450,2393,2024-08-01,Transfer,49924.20,Dining,Mobile,Completed
48487,48488,1930,6688,2025-03-09,Withdrawal,49783.82,Grocery,ATM,Failed
49719,49720,2833,2335,2025-09-06,Purchase,49738.94,Travel,Online,Failed
81938,81939,98,2192,2024-05-31,Withdrawal,49681.50,Education,Online,Completed
39031,39032,179,2889,2024-11-03,Purchase,49659.60,Utilities,Phone,Completed
2742,2743,2561,2362,2024-01-11,Purchase,49644.43,Retail,Phone,Failed
7020,7021,1520,3452,2024-10-28,Purchase,49630.85,Transportation,Phone,Completed
75342,75343,3110,6191,2024-08-15,Payment,49539.00,Travel,Mobile,Completed
80124,80125,3412,7465,2025-06-29,Transfer,49517.79,Entertainment,Phone,Completed
67402,67403,1835,6337,2024-03-15,Payment,49478.33,Entertainment,ATM,Completed
70888,70889,3926,4223,2024-08-24,Deposit,49387.25,Utilities,Phone,Pending
12602,12603,1184,3350,2025-04-12,Transfer,49376.07,Utilities,Branch,Failed
22492,22493,2319,1790,2025-06-05,Withdrawal,49362.84,Grocery,ATM,Completed
88786,88787,4894,614,2025-11-12,Purchase,49308.12,Grocery,ATM,Completed
3917,3918,2967,5240,2025-02-16,Purchase,49307.56,Travel,Phone,Completed
8812,8813,3123,1469,2024-03-17,Transfer,49285.90,Travel,Branch,Failed
17888,17889,3455,4127,2024-01-20,Transfer,49279.97,Dining,Branch,Completed
55450,55451,2924,3097,2024-05-22,Deposit,49278.40,Transportation,Phone,Pending
21568,21569,1063,2071,2025-07-25,Payment,49198.43,Healthcare,Mobile,Completed
52031,52032,4327,2495,2024-10-19,Payment,49101.40,Healthcare,Branch,Completed

In [15]:
quality_summary = pd.DataFrame({
    "Dataset": [
        "Customers",
        "Accounts",
        "Transactions",
        "Products"
    ],
    "Rows": [
        len(customers),
        len(accounts),
        len(transactions),
        len(products)
    ],
    "Columns": [
        customers.shape[1],
        accounts.shape[1],
        transactions.shape[1],
        products.shape[1]
    ]
})

quality_summary

        Dataset    Rows  Columns
0     Customers    5000        8
1      Accounts    7500        6
2  Transactions  100000        9
3      Products      10        4

In [16]:
transactions.to_csv("../data/processed/transactions_clean.csv",index=False)